### ISSUE TITLE
"iw" hebrew

### ISSUE THREAD

**Issue by kangoo13** [whitecube/lingua#2]
Could you consider adding "iw" as hebrew iso 639 code ? It is the former code but still used by many websites.

https://en.wikipedia.org/wiki/IW (category Other uses)

Thank you!

**Comment by kangoo13** [comment]
Yes that's it for the first question,

As for the second, we should just be able to detect that "iw" is hebrew, we could consider many ways like an 'outdated' language code key in languages.php or something else. Because when the language is detected and we ask back for the iso6391 code it should returns indeed "he" and not "iw"

**Comment by voidgraphics** [comment]
We could make that work. I'll get on it in a couple hours.

**Comment by kangoo13** [comment]
Thank you ! If you need any help I am at your disposal :+1:

**Comment by voidgraphics** [comment]
It should work now. I have added the "iw" deprecated code for Hebrew, but if you can think of other instances where we could add deprecated codes, we would gladly accept PR's!

To do this, in the `languages.php` file, you can add a `deprecated` key, like so:

```php
[
    'name' => 'hebrew',
    'native' => 'עברית',
    'iso-639-1' => 'he',
    'iso-639-2t' => 'heb',
    'iso-639-2b' => 'heb',
    'iso-639-3' => 'heb',
    'countries' => ['IL' => 'Israel'],
    'deprecated' => [
        'iso-639-1' => 'iw'
    ],
    'scripts' => []
],
```

**Comment by voidgraphics** [comment]
You can update your dependency to 1.0.2 to get the changes. 🙌
