### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by AndrewHaine** [whitecube/lingua#5]
Hey there,

The current composer dependencies state php version `^7.0`, are there any plans to make this package commpatible with PHP 8 in the future?

Thanks,

**Comment by Nyratas** [comment]
Hi @AndrewHaine,

We certainly plan to make this package compatible with PHP8. However, due to our current workload I cannot say when this will happen. A PR addressing this issue would help.

Have a great day.

**Comment by Nyratas** [comment]
Thank you everybody. @Wirone's PR has been released under version 1.1.0.

**Comment by AndrewHaine** [comment]
Thank you all! :)
